spring.application.name=taskmanager

#H2 DB config, new memory db called taskdb
spring.datasource.url=jdbc:h2:mem:taskdb
#Tells Spring which JDBC driver class to use to connect to db
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

#JPA config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#Auto create and update tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console config
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console